# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: |
        docker build -t your-app:${{ github.sha }} .
    
    - name: Deploy to production
      run: |
        # Add your deployment commands here
        # e.g., push to container registry, update kubernetes
        echo "Deploying to production..."